---------------------------------------------------------------------------------- 
-- $URL: https://source.sakaiproject.org/contrib/etudes/sakai-jforum/tags/2.8.1/jforum-tool/src/webapp/WEB-INF/config/database/conversion/jforum_2_8_m1-2_8_m2_mysql_conversion.sql $ 
-- $Id: jforum_2_8_m1-2_8_m2_mysql_conversion.sql 69107 2010-07-08 21:14:16Z murthy@etudes.org $ 
----------------------------------------------------------------------------------- 
-- 
-- Copyright (c) 2010 Etudes, Inc. 
-- 
-- Licensed under the Apache License, Version 2.0 (the "License"); 
-- you may not use this file except in compliance with the License. 
-- You may obtain a copy of the License at 
-- 
-- http://www.apache.org/licenses/LICENSE-2.0 
-- 
-- Unless required by applicable law or agreed to in writing, software 
-- distributed under the License is distributed on an "AS IS" BASIS, 
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
-- See the License for the specific language governing permissions and 
-- limitations under the License. 
----------------------------------------------------------------------------------
--------------------------------------------------------------------------
-- This is for MySQL JForum2.8.m1 JForum 2.8.m2
--------------------------------------------------------------------------
--Note : Before running this script back up the updated tables

--private messages priority
ALTER TABLE jforum_privmsgs ADD COLUMN privmsgs_priority TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 AFTER privmsgs_replied;