/**********************************************************************************
 * $URL: https://source.sakaiproject.org/contrib/etudes/sakai-jforum/tags/2.8.1/jforum-tool/src/java/org/etudes/jforum/dao/generic/GenericSmilieDAO.java $ 
 * $Id: GenericSmilieDAO.java 55493 2008-12-01 22:55:48Z murthy@etudes.org $ 
 *********************************************************************************** 
 * 
 * Copyright (c) 2008 Etudes, Inc. 
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 * limitations under the License. 
 * 
 * Portions completed before July 1, 2004 Copyright (c) 2003, 2004 Rafael Steil, All rights reserved, licensed under the BSD license. 
 * http://www.opensource.org/licenses/bsd-license.php 
 * 
 * Redistribution and use in source and binary forms, 
 * with or without modification, are permitted provided 
 * that the following conditions are met: 
 * 
 * 1) Redistributions of source code must retain the above 
 * copyright notice, this list of conditions and the 
 * following disclaimer. 
 * 2) Redistributions in binary form must reproduce the 
 * above copyright notice, this list of conditions and 
 * the following disclaimer in the documentation and/or 
 * other materials provided with the distribution. 
 * 3) Neither the name of "Rafael Steil" nor 
 * the names of its contributors may be used to endorse 
 * or promote products derived from this software without 
 * specific prior written permission. 
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT 
 * HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, 
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL 
 * THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE 
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, 
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER 
 * IN CONTRACT, STRICT LIABILITY, OR TORT 
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE 
 ***********************************************************************************/
package org.etudes.jforum.dao.generic;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.etudes.jforum.JForum;
import org.etudes.jforum.entities.Smilie;
import org.etudes.jforum.util.preferences.SystemGlobals;


/**
 * @author Rafael Steil
 */
public class GenericSmilieDAO extends AutoKeys implements org.etudes.jforum.dao.SmilieDAO {

	/** 
	 * @see net.jforum.repository.SmilieDAO#addNew(org.etudes.jforum.entities.Smilie)
	 */
	public int addNew(Smilie smilie) throws Exception 
	{
		PreparedStatement p = this.getStatementForAutoKeys("SmiliesModel.addNew");
		
		p.setString(1, smilie.getCode());
		p.setString(2, smilie.getUrl());
		p.setString(3, smilie.getDiskName());
		
		this.setAutoGeneratedKeysQuery(SystemGlobals.getSql("SmiliesModel.lastGeneratedSmilieId"));
		int id = this.executeAutoKeysQuery(p);

		p.close();
		return id;
	}

	/** 
	 * @see net.jforum.repository.SmilieDAO#delete(int)
	 */
	public void delete(int id) throws Exception 
	{
		PreparedStatement p = JForum.getConnection().prepareStatement(SystemGlobals.getSql("SmiliesModel.delete"));
		p.setInt(1, id);
		p.executeUpdate();
		
		p.close();
	}

	/** 
	 * @see net.jforum.repository.SmilieDAO#update(org.etudes.jforum.entities.Smilie)
	 */
	public void update(Smilie smilie) throws Exception 
	{
		PreparedStatement p = JForum.getConnection().prepareStatement(SystemGlobals.getSql("SmiliesModel.update"));
		p.setString(1, smilie.getCode());
		p.setString(2, smilie.getUrl());
		p.setString(3, smilie.getDiskName());
		p.setInt(4, smilie.getId());
		
		p.executeUpdate();
		p.close();
	}
	
	private Smilie getSmilie(ResultSet rs) throws SQLException
	{
		Smilie s = new Smilie();
		
		s.setId(rs.getInt("smilie_id"));
		s.setCode(rs.getString("code"));
		s.setUrl(rs.getString("url"));
		s.setDiskName(rs.getString("disk_name"));
		
		return s;
	}

	/** 
	 * @see net.jforum.repository.SmilieDAO#selectAll()
	 */
	public List selectAll() throws Exception 
	{
		List l = new ArrayList();
		
		PreparedStatement p = JForum.getConnection().prepareStatement(SystemGlobals.getSql("SmiliesModel.selectAll"));
		ResultSet rs = p.executeQuery();
		while (rs.next()) {
			l.add(this.getSmilie(rs));
		}
		
		rs.close();
		p.close();
		
		return l;
	}

	/** 
	 * @see org.etudes.jforum.dao.SmilieDAO#selectById(int)
	 */
	public Smilie selectById(int id) throws Exception 
	{
		PreparedStatement p = JForum.getConnection().prepareStatement(SystemGlobals.getSql("SmiliesModel.selectById"));
		p.setInt(1, id);
		
		Smilie s = new Smilie();
		
		ResultSet rs = p.executeQuery();
		if (rs.next()) {
			s = this.getSmilie(rs);
		}
		
		rs.close();
		p.close();
		
		return s;
	}
}
