CREATE TABLE melete_bookmark (
 BOOKMARK_ID NUMBER(11) DEFAULT '0' NOT NULL,
 SECTION_ID NUMBER(11) DEFAULT '0' NOT NULL,
 USER_ID VARCHAR2(99) DEFAULT NULL,
 SITE_ID VARCHAR2(99) DEFAULT NULL,
 TITLE VARCHAR2(99) DEFAULT '' NOT NULL,
 NOTES CLOB,
 LAST_VISITED NUMBER(1) DEFAULT NULL,
 PRIMARY KEY (BOOKMARK_ID),
 CONSTRAINT FK_MB_MS FOREIGN KEY (SECTION_ID) REFERENCES melete_section(SECTION_ID)
); 