CREATE TABLE melete_bookmark (
 BOOKMARK_ID NUMBER(11) DEFAULT '0' NOT NULL,
 SECTION_ID NUMBER(11) DEFAULT '0' NOT NULL,
 USER_ID VARCHAR2(99) DEFAULT NULL,
 SITE_ID VARCHAR2(99) DEFAULT NULL,
 TITLE VARCHAR2(99) DEFAULT '' NOT NULL,
 NOTES CLOB,
 LAST_VISITED NUMBER(1) DEFAULT NULL,
 PRIMARY KEY (BOOKMARK_ID),
 CONSTRAINT FK_MB_MS FOREIGN KEY (SECTION_ID) REFERENCES melete_section(SECTION_ID)
); 

alter table melete_resource modify COPYRIGHT_YEAR varchar2(255);
alter table melete_user_preference modify COPYRIGHT_YEAR varchar2(255); 

CREATE TABLE melete_special_access (
  ACCESS_ID number(11) default '0',
  MODULE_ID number(11) default '0',
  USERS CLOB NOT NULL,
  START_DATE timestamp default NULL,
  END_DATE timestamp default NULL,
  PRIMARY KEY (ACCESS_ID),
  CONSTRAINT FK_MSA_MM FOREIGN KEY(MODULE_ID) REFERENCES melete_module(MODULE_ID)
);